loopbackio/strong-error-handler

lib/handler.js, test/handler.test.js
Handle error from res.statusCode
>by miroslav:
here, we are calling `res.status` instead of setting the status on the error object.
https://github.com/strongloop/strong-remoting/blob/aa391d2e65460196ae2a59493f9dd4844622f35d/lib/http-context.js#L391
test case from strong-remoting
https://github.com/strongloop/strong-remoting/blob/aa391d2e65460196ae2a59493f9dd4844622f35d/test/rest.test.js#L2021-L2032
=> Handle error from res.statusCode

lib/data-builder.js, test/handler.test.js
Because err.message is also not enumerable,
therefore needs to be explicited added to the data obj
=> Include err.message for debug data

lib/clone.js, lib/data-builder.js, test/handler.test.js
This is to preserve behavior from strong-remoting rest adapter
=> Remove statusCode from details in Array errors

lib/content-negotiation.js, lib/send-xml.js, package.json, test/handler.test.js
This adds xml support
- strongloop/strong-error-handler#4
=> add xml error output support

lib/data-builder.js, lib/handler.js, test/handler.test.js
Allow specifying an array of safe field properties to be included in 4xx and 5xx errors #7
- #7 Implement "safeFields" option
=> Allow specifying safeFields #7

lib/data-builder.js, test/handler.test.js
Fix the problem introduced in #37 which causes downstream loopback tests to fail.
cc @zbarbuto
=> Stop adding safeFields to original options arg

README.md, lib/data-builder.js, test/handler.test.js
Allows a machine-readable `code` property through with error responses
A number of the components of loopback such as strong-remoting and loopback itself include a machine readable `error.code` property (as an example, see [this commit](https://github.com/strongloop/loopback/commit/a028d9d19887e2518a6e2ce9fb3b5194d395ed5c)). This is very useful as it can be use for, say, client-side error translation for example. The current state of strong-error-handler strips out these properties, defeating the purpose of having them in the first place.
This PR allows `error.code` through.
- None
=> Add machine readable code property

README.md
fixes #4 
I noticed [in strong-remoting we supported `application/xml`](https://github.com/strongloop/strong-remoting/blob/0d8173c85ab31bb1927dfb469d7d55cdd2c3af8d/lib/http-context.js#L25) but we dont have it in content-negotiation [here](https://github.com/strongloop/strong-error-handler/blob/fb68b611c19852de8e71115f3fc28cb9da38c745/lib/content-negotiation.js#L29)
=> Update readme with added XML support

package.json
Having some issues caused by js2xmlparsers dependency on xmlcreate at version 0.1.1 so updated.
- None
=> Bump js2xmlparser dependency to version 3.0.0

README.md, lib/content-negotiation.js, test/handler.test.js
added `contenType` option for passing mandatory response content type
- None
=> Add contentType option for passing mandatory type

README.md
the json format is valid now
- None
=> fixed json typo of server/middleware.json

.npmrc, package.json, test/handler.test.js, views/default-error.ejs
- Added XSS to HTML and JSON output
- Bumped Version of EJS for recent security vulnerability
The original issue was around output of the HTML, but the logger still produced XSS issues in JSON. I included a fix for that too. I did not do a sanitize function in `lib/data-builder.js` because it threw off the sanitation in the XML portion. I included tests for HTML, XML and JSON. 
- connect to #66 
=> Escape strings in HTML output (XSS fix)

lib/data-builder.js, test/handler.test.js
Resolves issue in #71 where having `statusCode` in `safeFields` would result in an undefined response status code.
- Closes #71 
=> Undefined safeFields revert to data #71

.travis.yml, README.md, lib/content-negotiation.js, package.json, test/handler.test.js
Part of work to release a new semver version.
Follow the story on #73 for reasoning behind releasing as a new major version.
**NOTE**: Please look at just the first review to see the actual changes in the test file
- connect to <link_to_referenced_issue>
=> Drop node 4, update dependencies and status on maintenance

lib/data-builder.js, test/handler.test.js
Previously when an array of errors are encountered, full information on the errors was not revealed to the response unless `debug` mode was specifically enabled; even if `safeFields` was set the properties in it would not show in the response. This PR fixes this.
- fixes #45
- connect to <link_to_referenced_issue>
=> Allow safeFields to work with arrays

README.md, index.d.ts, lib/handler.js, package.json, test/handler.test.js
related to strongloop/loopback-next#1598
- connect to <link_to_referenced_issue>
=> add types and introduce writeErrorToResponse

.travis.yml, README.md, index.d.ts, lib/handler.js, lib/send-html.js, lib/send-json.js, lib/send-xml.js, package.json, test/handler.test.js, views/default-error.ejs
1. Drop Node 8.x support
2. Upgrade dependencies
3. Add `options.rootProperty` to control the root property of json/xml response
- OpenAPI specs can define `error` object in the schema. Such endpoints need to send conforming errors to the client. Always adding `error` as the root property break such cases.
=> feat: Add options.rootProperty

README.md, lib/logger.js, package.json
Before this commit, we logged messages saying "unhandled error". This was often creating confusion for our users, it seems like the error was not handled at all, when in fact it was caught by the configured error handler and converted into a proper HTTP error response.
In this commit, I am changing the messaging to use "request failed" instead.
While this change is not affecting application developers, it may break tooling processing logs if the tool relies on a specific format of error messages. To be safe, I am labelling this change as breaking.
Close #54
=> Reword log messages for better clarity

.github/ISSUE_TEMPLATE.md, CONTRIBUTING.md, package.json
As part of https://github.com/strongloop/loopback-next/issues/7595
Signed-off-by: Diana Lau <dhmlau@ca.ibm.com>
- connect to <link_to_referenced_issue>
=> chore: move repo to loopbackio org

lib/send-html.js, test/handler.test.mjs
Avoid rendering undefined/null values from errors as `[Object object]` in the HTML output.
- Fixes: https://github.com/loopbackio/strong-error-handler/issues/447
=> fix(html): avoid rendering [Object object] for undefined values in Handlebars template
